### ISSUE TITLE
Multiple build issues

### ISSUE THREAD

**Issue by hazeycode** [kubkon/zig-ios-example#9]
Tested using
- MacOS Ventura 13.3.1
- Xcode 14.3.1
- Zig 0.11.0-dev.3947+89396ff02

1. SDK path is not autmatically resolved. 
  Work around: specify sysroot i.e. `zig build --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -Dtarget=aarch64-ios-simulator`

2. Framework search paths are not added.
  Work around: Change `if (!(comptime builtin.os.tag.isDarwin())) {` to `if ((comptime builtin.os.tag.isDarwin())) {` in build.zig

3. App installed on Simulator but will not run:
  ```
  An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=4):
  Simulator device returned an error for the requested operation.
  This app needs to be updated by the developer to work on this version of iOS.
  Failed to find matching arch for input file: /Users/chris/Library/Developer/CoreSimulator/Devices/366E3E76-6826-41E9-AFDA-0010D23DB12C/data/Library/Caches/com.apple.mobile.installd.staging/temp.J7z86b/extracted/MadeWithZig.app/app
  Underlying error (domain=IXUserPresentableErrorDomain, code=4):
	  “MadeWithZig” Needs To Be Updated
	  This app needs to be updated by the developer to work on this version of iOS.`
  ```
  I couldn't find a work around for this yet. I have tried different Simulator versions, editing the plist, etc.

**Comment by kubkon** [comment]
Can you verify that 1. and 2. are now fixed, and create a separate issue for 3. with exact info on your runtime environment?

**Comment by hazeycode** [comment]
@kubkon I can confirm 1 & 2 are fixed
